apply: False
save: True

method:
  _target_: main.PyramidalColorDescriptor
  layers: 4
  channels: [1,2]

colorspace:
  _target_: main.Color_Preprocessor.convert2lab

kwargs:
  range: [0, 256]
  bins: 64
